
INSERT INTO pokemon(nome,tipo) VALUES('Bulbasaur','Grama-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES('Ivysaur','Grama-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES('Venosaur','Grama-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES('Charmander', 'Fogo');
INSERT INTO pokemon(nome,tipo) VALUES('Charmeleon', 'Fogo');
INSERT INTO pokemon(nome,tipo) VALUES('Charizard', 'Fogo-Voador');
INSERT INTO pokemon(nome,tipo) VALUES('Squirtle', 'Água');
INSERT INTO pokemon(nome,tipo) VALUES('Wartortle', 'Água');
INSERT INTO pokemon(nome,tipo) VALUES('Blastoise', 'Água');
INSERT INTO pokemon(nome,tipo) VALUES('Caterpie', 'Inseto');
INSERT INTO pokemon(nome,tipo) VALUES('Metapod', 'Inseto');
INSERT INTO pokemon(nome,tipo) VALUES('Butterfree', 'Inseto-Voador');
INSERT INTO pokemon(nome,tipo) VALUES('Weedle', 'Inseto');
INSERT INTO pokemon(nome,tipo) VALUES('Kakuna', 'Inseto');
INSERT INTO pokemon(nome,tipo) VALUES('Beedrill', 'Inseto-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Pidgey', 'Voador');
INSERT INTO pokemon(nome,tipo) VALUES( 'Pidgeotto', 'Voador');
INSERT INTO pokemon(nome,tipo) VALUES( 'Pidgeot', 'Voador');
INSERT INTO pokemon(nome,tipo) VALUES( 'Rattata', 'Normal');
INSERT INTO pokemon(nome,tipo) VALUES( 'Raticate', 'Normal');
INSERT INTO pokemon(nome,tipo) VALUES('Spearow', 'Voador');
INSERT INTO pokemon(nome,tipo) VALUES( 'Fearow', 'Voador');
INSERT INTO pokemon(nome,tipo) VALUES( 'Ekans', 'Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Arbok', 'Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Pikachu', 'Elétrico');
INSERT INTO pokemon(nome,tipo) VALUES( 'Raichu', 'Elétrico');
INSERT INTO pokemon(nome,tipo) VALUES('Sandshrew', 'Terra');
INSERT INTO pokemon(nome,tipo) VALUES( 'Sandslash', 'Terra');
INSERT INTO pokemon(nome,tipo) VALUES('NidoranF', 'Terra-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES('Nidorina', 'Terra-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Nidoqueen', 'Terra-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'NidoranM', 'Terra-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Nidorino', 'Terra-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES('Nidoking', 'Terra-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Clefairy', 'Normal');
INSERT INTO pokemon(nome,tipo) VALUES( 'Clefable', 'Normal');
INSERT INTO pokemon(nome,tipo) VALUES('Vulpix', 'Fogo');
INSERT INTO pokemon(nome,tipo) VALUES( 'Ninetales', 'Fogo');
INSERT INTO pokemon(nome,tipo) VALUES( 'Jigglypuff', 'Normal');
INSERT INTO pokemon(nome,tipo) VALUES( 'Wigglytuff', 'Normal');
INSERT INTO pokemon(nome,tipo) VALUES( 'Zubat', 'Voador-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Golbat', 'Voador-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Oddish', 'Grama-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Gloom', 'Grama-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES('Vileplume', 'Grama-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Paras', 'Inseto-Grama');
INSERT INTO pokemon(nome,tipo) VALUES('Parasect', 'Inseto-Grama');
INSERT INTO pokemon(nome,tipo) VALUES('Venonat', 'Inseto-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES('Venomoth', 'Inseto-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Diglett', 'Terra');
INSERT INTO pokemon(nome,tipo) VALUES('Dugtrio', 'Terra');
INSERT INTO pokemon(nome,tipo) VALUES( 'Meowth', 'Normal');
INSERT INTO pokemon(nome,tipo) VALUES( 'Persian', 'Normal');
INSERT INTO pokemon(nome,tipo) VALUES('Psyduck', 'Água');
INSERT INTO pokemon(nome,tipo) VALUES( 'Golduck', 'Água');
INSERT INTO pokemon(nome,tipo) VALUES( 'Mankey', 'Lutador');
INSERT INTO pokemon(nome,tipo) VALUES( 'Primeape', 'Lutador');
INSERT INTO pokemon(nome,tipo) VALUES('Growlithe', 'Fogo');
INSERT INTO pokemon(nome,tipo) VALUES( 'Arcanine', 'Fogo');
INSERT INTO pokemon(nome,tipo) VALUES( 'Poliwag', 'Água');
INSERT INTO pokemon(nome,tipo) VALUES( 'Poliwhirl','Água');
INSERT INTO pokemon(nome,tipo) VALUES( 'Poliwrath', 'Água-lutador');
INSERT INTO pokemon(nome,tipo) VALUES( 'Abra', 'Psiquico');
INSERT INTO pokemon(nome,tipo) VALUES( 'Kadabra', 'Psiquico');
INSERT INTO pokemon(nome,tipo) VALUES( 'Alakazam', 'Psiquico');
INSERT INTO pokemon(nome,tipo) VALUES( 'Machop', 'Lutador');
INSERT INTO pokemon(nome,tipo) VALUES( 'Machoke', 'Lutador');
INSERT INTO pokemon(nome,tipo) VALUES( 'Machamp', 'Lutador');
INSERT INTO pokemon(nome,tipo) VALUES( 'Bellsprout', 'Grama-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Weepinbell', 'Grama-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Victreebel', 'Grama-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Tentacool', 'Água-Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Tentacruel', 'Água-Venesoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Geodude', 'Pedra');
INSERT INTO pokemon(nome,tipo) VALUES( 'Graveler', 'Pedra');
INSERT INTO pokemon(nome,tipo) VALUES( 'Golem', 'Pedra');
INSERT INTO pokemon(nome,tipo) VALUES( 'Ponyta', 'Fogo');
INSERT INTO pokemon(nome,tipo) VALUES( 'Rapidash', 'Fogo');
INSERT INTO pokemon(nome,tipo) VALUES( 'Slowpoke', 'Água');
INSERT INTO pokemon(nome,tipo) VALUES( 'Slowbro', 'Água-Psiquico');
INSERT INTO pokemon(nome,tipo) VALUES( 'Magnemite', 'Elétrico');
INSERT INTO pokemon(nome,tipo) VALUES( 'Magneton', 'Elétrico');
INSERT INTO pokemon(nome,tipo) VALUES( 'Farfetch''d', 'Normal-Voador');
INSERT INTO pokemon(nome,tipo) VALUES( 'Doduo', 'Normal-Voador');
INSERT INTO pokemon(nome,tipo) VALUES( 'Dodrio', 'Normal-Voador');
INSERT INTO pokemon(nome,tipo) VALUES( 'Seel', 'Água-Gelo');
INSERT INTO pokemon(nome,tipo) VALUES( 'Dewgong', 'Água-Gelo');
INSERT INTO pokemon(nome,tipo) VALUES( 'Grimer', 'Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Muk', 'Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Shellder', 'Água');
INSERT INTO pokemon(nome,tipo) VALUES( 'Cloyster', 'Água-Gelo');
INSERT INTO pokemon(nome,tipo) VALUES( 'Gastly', 'Fantasma');
INSERT INTO pokemon(nome,tipo) VALUES( 'Haunter', 'Fantasma');
INSERT INTO pokemon(nome,tipo) VALUES( 'Gengar','Fantasma');
INSERT INTO pokemon(nome,tipo) VALUES( 'Onix', 'Pedra');
INSERT INTO pokemon(nome,tipo) VALUES( 'Drowzee', 'Psiquico');
INSERT INTO pokemon(nome,tipo) VALUES('Hypno', 'Psiquico');
INSERT INTO pokemon(nome,tipo) VALUES('Krabby', 'Água');
INSERT INTO pokemon(nome,tipo) VALUES('Kingler', 'Água');
INSERT INTO pokemon(nome,tipo) VALUES('Voltorb', 'Elétrico');
INSERT INTO pokemon(nome,tipo) VALUES( 'Electrode','Elétrico');
INSERT INTO pokemon(nome,tipo) VALUES( 'Exeggcute', 'Planta-Psiquico');
INSERT INTO pokemon(nome,tipo) VALUES( 'Exeggutor', 'Planta-Psiquico');
INSERT INTO pokemon(nome,tipo) VALUES( 'Cubone', 'Terra');
INSERT INTO pokemon(nome,tipo) VALUES( 'Marowak', 'Terra');
INSERT INTO pokemon(nome,tipo) VALUES( 'Hitmonlee', 'Lutador');
INSERT INTO pokemon(nome,tipo) VALUES('Hitmonchan', 'Lutador');
INSERT INTO pokemon(nome,tipo) VALUES('Lickitung', 'Normal');
INSERT INTO pokemon(nome,tipo) VALUES('Koffing', 'Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Weezing', 'Venenoso');
INSERT INTO pokemon(nome,tipo) VALUES( 'Rhyhorn', 'Pedra-Terra');
INSERT INTO pokemon(nome,tipo) VALUES( 'Rhydon', 'Pedra-Terra');
INSERT INTO pokemon(nome,tipo) VALUES( 'Chansey', 'Normal');
INSERT INTO pokemon(nome,tipo) VALUES( 'Tangela', 'Grama');
INSERT INTO pokemon(nome,tipo) VALUES( 'Kangaskhan', 'Normal');
INSERT INTO pokemon(nome,tipo) VALUES( 'Horsea', 'Água');
INSERT INTO pokemon(nome,tipo) VALUES( 'Seadra', 'Água');
INSERT INTO pokemon(nome,tipo) VALUES( 'Goldeen', 'Água');
INSERT INTO pokemon(nome,tipo) VALUES( 'Seaking', 'Água');
INSERT INTO pokemon(nome,tipo) VALUES( 'Staryu', 'Água');
INSERT INTO pokemon(nome,tipo) VALUES( 'Starmie', 'Água');
INSERT INTO pokemon(nome,tipo) VALUES( 'Mr. Mime', 'Psiquico');
INSERT INTO pokemon(nome,tipo) VALUES( 'Scyther', 'Inseto');
INSERT INTO pokemon(nome,tipo) VALUES( 'Jynx', 'Gelo-Psiquico');
INSERT INTO pokemon(nome,tipo) VALUES( 'Electabuzz', 'Elétrico');
INSERT INTO pokemon(nome,tipo) VALUES( 'Magmar', 'Fogo');
INSERT INTO pokemon(nome,tipo) VALUES( 'Pinsir', 'Inseto');
INSERT INTO pokemon(nome,tipo) VALUES( 'Tauros', 'Normal');
INSERT INTO pokemon(nome,tipo) VALUES( 'Magikarp', 'Água');
INSERT INTO pokemon(nome,tipo) VALUES( 'Gyarados', 'Água-Voador');
INSERT INTO pokemon(nome,tipo) VALUES( 'Lapras', 'Água-Gelo');
INSERT INTO pokemon(nome,tipo) VALUES( 'Ditto', 'Normal');
INSERT INTO pokemon(nome,tipo) VALUES( 'Eevee', 'Normal');
INSERT INTO pokemon(nome,tipo) VALUES( 'Vaporeon', 'Água');
INSERT INTO pokemon(nome,tipo) VALUES( 'Jolteon', 'Elétrico');
INSERT INTO pokemon(nome,tipo) VALUES( 'Flareon', 'Fogo');
INSERT INTO pokemon(nome,tipo) VALUES( 'Porygon', 'Normal');
INSERT INTO pokemon(nome,tipo) VALUES( 'Omanyte', 'Água-Pedra');
INSERT INTO pokemon(nome,tipo) VALUES( 'Omastar', 'Água-Pedra');
INSERT INTO pokemon(nome,tipo) VALUES( 'Kabuto', 'Água-Pedra');
INSERT INTO pokemon(nome,tipo) VALUES( 'Kabutops', 'Água-Peda');
INSERT INTO pokemon(nome,tipo) VALUES( 'Aerodactyl', 'Voador-Pedra');
INSERT INTO pokemon(nome,tipo) VALUES( 'Snorlax', 'Normal');
INSERT INTO pokemon(nome,tipo) VALUES( 'Articuno', 'Voador-Gelo');
INSERT INTO pokemon(nome,tipo) VALUES( 'Zapdos', 'Voador-Eletrico');
INSERT INTO pokemon(nome,tipo) VALUES( 'Moltres', 'Voador-Fogo');
INSERT INTO pokemon(nome,tipo) VALUES( 'Dratini', 'Dragão');
INSERT INTO pokemon(nome,tipo) VALUES( 'Dragonair', 'Dragão');
INSERT INTO pokemon(nome,tipo) VALUES( 'Dragonite', 'Dragão-Voador');
INSERT INTO pokemon(nome,tipo) VALUES( 'Mewtwo', 'Psiquico');
INSERT INTO pokemon(nome,tipo) VALUES( 'Mew', 'Psiquico');
