
INSERT INTO pokemon (id, nome, tipo) VALUES(1,'Bulbasaur','Grama-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(2, 'Ivysaur', 'Grama-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(3, 'Venusaur', 'Grama-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(4, 'Charmander', 'Fogo');
INSERT INTO pokemon (id, nome, tipo) VALUES (5, 'Charmeleon', 'Fogo');
INSERT INTO pokemon (id, nome, tipo) VALUES (6, 'Charizard', 'Fogo-Voador');
INSERT INTO pokemon (id, nome, tipo) VALUES (7, 'Squirtle', 'Água');
INSERT INTO pokemon (id, nome, tipo) VALUES (8, 'Wartortle', 'Água');
INSERT INTO pokemon (id, nome, tipo) VALUES (9, 'Blastoise', 'Água');
INSERT INTO pokemon (id, nome, tipo) VALUES (10, 'Caterpie', 'Inseto');
INSERT INTO pokemon (id, nome, tipo) VALUES (11, 'Metapod', 'Inseto');
INSERT INTO pokemon (id, nome, tipo) VALUES (12, 'Butterfree', 'Inseto-Voador');
INSERT INTO pokemon (id, nome, tipo) VALUES (13, 'Weedle', 'Inseto');
INSERT INTO pokemon (id, nome, tipo) VALUES (14, 'Kakuna', 'Inseto');
INSERT INTO pokemon (id, nome, tipo) VALUES (15, 'Beedrill', 'Inseto-Venenoso');

INSERT INTO pokemon (id, nome, tipo) VALUES(16, 'Pidgey', 'Voador');
INSERT INTO pokemon (id, nome, tipo) VALUES(17, 'Pidgeotto', 'Voador');
INSERT INTO pokemon (id, nome, tipo) VALUES(18, 'Pidgeot', 'Voador');
INSERT INTO pokemon (id, nome, tipo) VALUES(19, 'Rattata', 'Normal');
INSERT INTO pokemon (id, nome, tipo) VALUES(20, 'Raticate', 'Normal');
INSERT INTO pokemon (id, nome, tipo) VALUES(21, 'Spearow', 'Voador');
INSERT INTO pokemon (id, nome, tipo) VALUES(22, 'Fearow', 'Voador');
INSERT INTO pokemon (id, nome, tipo) VALUES(23, 'Ekans', 'Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(24, 'Arbok', 'Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(25, 'Pikachu', 'Elétrico');
INSERT INTO pokemon (id, nome, tipo) VALUES(26, 'Raichu', 'Elétrico');
INSERT INTO pokemon (id, nome, tipo) VALUES(27, 'Sandshrew', 'Terra');
INSERT INTO pokemon (id, nome, tipo) VALUES(28, 'Sandslash', 'Terra');
INSERT INTO pokemon (id, nome, tipo) VALUES(29, 'NidoranF', 'Terra-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(30, 'Nidorina', 'Terra-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(31, 'Nidoqueen', 'Terra-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(32, 'NidoranM', 'Terra-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(33, 'Nidorino', 'Terra-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(34, 'Nidoking', 'Terra-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(35, 'Clefairy', 'Normal');
INSERT INTO pokemon (id, nome, tipo) VALUES(36, 'Clefable', 'Normal');
INSERT INTO pokemon (id, nome, tipo) VALUES(37, 'Vulpix', 'Fogo');
INSERT INTO pokemon (id, nome, tipo) VALUES(38, 'Ninetales', 'Fogo');
INSERT INTO pokemon (id, nome, tipo) VALUES(39, 'Jigglypuff', 'Normal');
INSERT INTO pokemon (id, nome, tipo) VALUES(40, 'Wigglytuff', 'Normal');
INSERT INTO pokemon (id, nome, tipo) VALUES(41, 'Zubat', 'Voador-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(42, 'Golbat', 'Voador-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(43, 'Oddish', 'Grama-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(44, 'Gloom', 'Grama-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(45, 'Vileplume', 'Grama-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(46, 'Paras', 'Inseto-Grama');
INSERT INTO pokemon (id, nome, tipo) VALUES(47, 'Parasect', 'Inseto-Grama');
INSERT INTO pokemon (id, nome, tipo) VALUES(48, 'Venonat', 'Inseto-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(49, 'Venomoth', 'Inseto-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(50, 'Diglett', 'Terra');
INSERT INTO pokemon (id, nome, tipo) VALUES(51, 'Dugtrio', 'Terra');
INSERT INTO pokemon (id, nome, tipo) VALUES(52, 'Meowth', 'Normal');
INSERT INTO pokemon (id, nome, tipo) VALUES(53, 'Persian', 'Normal');
INSERT INTO pokemon (id, nome, tipo) VALUES(54, 'Psyduck', 'Água');
INSERT INTO pokemon (id, nome, tipo) VALUES(55, 'Golduck', 'Água');
INSERT INTO pokemon (id, nome, tipo) VALUES(56, 'Mankey', 'Lutador');
INSERT INTO pokemon (id, nome, tipo) VALUES(57, 'Primeape', 'Lutador');
INSERT INTO pokemon (id, nome, tipo) VALUES(58, 'Growlithe', 'Fogo');
INSERT INTO pokemon (id, nome, tipo) VALUES(59, 'Arcanine', 'Fogo');
INSERT INTO pokemon (id, nome, tipo) VALUES(60, 'Poliwag', 'Água');
INSERT INTO pokemon (id, nome, tipo) VALUES(61, 'Poliwhirl','Água');
INSERT INTO pokemon (id, nome, tipo) VALUES(62, 'Poliwrath', 'Água-lutador');
INSERT INTO pokemon (id, nome, tipo) VALUES(63, 'Abra', 'Psiquico');
INSERT INTO pokemon (id, nome, tipo) VALUES(64, 'Kadabra', 'Psiquico');
INSERT INTO pokemon (id, nome, tipo) VALUES(65, 'Alakazam', 'Psiquico');
INSERT INTO pokemon (id, nome, tipo) VALUES(66, 'Machop', 'Lutador');
INSERT INTO pokemon (id, nome, tipo) VALUES(67, 'Machoke', 'Lutador');
INSERT INTO pokemon (id, nome, tipo) VALUES(68, 'Machamp', 'Lutador');
INSERT INTO pokemon (id, nome, tipo) VALUES(69, 'Bellsprout', 'Grama-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(70, 'Weepinbell', 'Grama-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(71, 'Victreebel', 'Grama-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(72, 'Tentacool', 'Água-Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(73, 'Tentacruel', 'Água-Venesoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(74, 'Geodude', 'Pedra');
INSERT INTO pokemon (id, nome, tipo) VALUES(75, 'Graveler', 'Pedra');
INSERT INTO pokemon (id, nome, tipo) VALUES(76, 'Golem', 'Pedra');
INSERT INTO pokemon (id, nome, tipo) VALUES(77, 'Ponyta', 'Fogo');
INSERT INTO pokemon (id, nome, tipo) VALUES(78, 'Rapidash', 'Fogo');
INSERT INTO pokemon (id, nome, tipo) VALUES(79, 'Slowpoke', 'Água');
INSERT INTO pokemon (id, nome, tipo) VALUES(80, 'Slowbro', 'Água-Psiquico');
INSERT INTO pokemon (id, nome, tipo) VALUES(81, 'Magnemite', 'Elétrico');
INSERT INTO pokemon (id, nome, tipo) VALUES(82, 'Magneton', 'Elétrico');
INSERT INTO pokemon (id, nome, tipo) VALUES(83, 'Farfetch''d', 'Normal-Voador');
INSERT INTO pokemon (id, nome, tipo) VALUES(84, 'Doduo', 'Normal-Voador');
INSERT INTO pokemon (id, nome, tipo) VALUES(85, 'Dodrio', 'Normal-Voador');
INSERT INTO pokemon (id, nome, tipo) VALUES(86, 'Seel', 'Água-Gelo');
INSERT INTO pokemon (id, nome, tipo) VALUES(87, 'Dewgong', 'Água-Gelo');
INSERT INTO pokemon (id, nome, tipo) VALUES(88, 'Grimer', 'Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(89, 'Muk', 'Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(90, 'Shellder', 'Água');
INSERT INTO pokemon (id, nome, tipo) VALUES(91, 'Cloyster', 'Água-Gelo');
INSERT INTO pokemon (id, nome, tipo) VALUES(92, 'Gastly', 'Fantasma');
INSERT INTO pokemon (id, nome, tipo) VALUES(93, 'Haunter', 'Fantasma');
INSERT INTO pokemon (id, nome, tipo) VALUES(94, 'Gengar','Fantasma');
INSERT INTO pokemon (id, nome, tipo) VALUES(95, 'Onix', 'Pedra');
INSERT INTO pokemon (id, nome, tipo) VALUES(96, 'Drowzee', 'Psiquico');
INSERT INTO pokemon (id, nome, tipo) VALUES(97, 'Hypno', 'Psiquico');
INSERT INTO pokemon (id, nome, tipo) VALUES(98, 'Krabby', 'Água');
INSERT INTO pokemon (id, nome, tipo) VALUES(99, 'Kingler', 'Água');
INSERT INTO pokemon (id, nome, tipo) VALUES(100, 'Voltorb', 'Elétrico');
INSERT INTO pokemon (id, nome, tipo) VALUES(101, 'Electrode','Elétrico');
INSERT INTO pokemon (id, nome, tipo) VALUES(102, 'Exeggcute', 'Planta-Psiquico');
INSERT INTO pokemon (id, nome, tipo) VALUES(103, 'Exeggutor', 'Planta-Psiquico');
INSERT INTO pokemon (id, nome, tipo) VALUES(104, 'Cubone', 'Terra');
INSERT INTO pokemon (id, nome, tipo) VALUES(105, 'Marowak', 'Terra');
INSERT INTO pokemon (id, nome, tipo) VALUES(106, 'Hitmonlee', 'Lutador');
INSERT INTO pokemon (id, nome, tipo) VALUES(107, 'Hitmonchan', 'Lutador');
INSERT INTO pokemon (id, nome, tipo) VALUES(108, 'Lickitung', 'Normal');
INSERT INTO pokemon (id, nome, tipo) VALUES(109, 'Koffing', 'Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(110, 'Weezing', 'Venenoso');
INSERT INTO pokemon (id, nome, tipo) VALUES(111, 'Rhyhorn', 'Pedra-Terra');
INSERT INTO pokemon (id, nome, tipo) VALUES(112, 'Rhydon', 'Pedra-Terra');
INSERT INTO pokemon (id, nome, tipo) VALUES(113, 'Chansey', 'Normal');
INSERT INTO pokemon (id, nome, tipo) VALUES(114, 'Tangela', 'Grama');
INSERT INTO pokemon (id, nome, tipo) VALUES(115, 'Kangaskhan', 'Normal');
INSERT INTO pokemon (id, nome, tipo) VALUES(116, 'Horsea', 'Água');
INSERT INTO pokemon (id, nome, tipo) VALUES(117, 'Seadra', 'Água');
INSERT INTO pokemon (id, nome, tipo) VALUES(118, 'Goldeen', 'Água');
INSERT INTO pokemon (id, nome, tipo) VALUES(119, 'Seaking', 'Água');
INSERT INTO pokemon (id, nome, tipo) VALUES(120, 'Staryu', 'Água');
INSERT INTO pokemon (id, nome, tipo) VALUES(121, 'Starmie', 'Água');
INSERT INTO pokemon (id, nome, tipo) VALUES(122, 'Mr. Mime', 'Psiquico');
INSERT INTO pokemon (id, nome, tipo) VALUES(123, 'Scyther', 'Inseto');
INSERT INTO pokemon (id, nome, tipo) VALUES(124, 'Jynx', 'Gelo-Psiquico');
INSERT INTO pokemon (id, nome, tipo) VALUES(125, 'Electabuzz', 'Elétrico');
INSERT INTO pokemon (id, nome, tipo) VALUES(126, 'Magmar', 'Fogo');
INSERT INTO pokemon (id, nome, tipo) VALUES(127, 'Pinsir', 'Inseto');
INSERT INTO pokemon (id, nome, tipo) VALUES(128, 'Tauros', 'Normal');
INSERT INTO pokemon (id, nome, tipo) VALUES(129, 'Magikarp', 'Água');
INSERT INTO pokemon (id, nome, tipo) VALUES(130, 'Gyarados', 'Água-Voador');
INSERT INTO pokemon (id, nome, tipo) VALUES(131, 'Lapras', 'Água-Gelo');
INSERT INTO pokemon (id, nome, tipo) VALUES(132, 'Ditto', 'Normal');
INSERT INTO pokemon (id, nome, tipo) VALUES(133, 'Eevee', 'Normal');
INSERT INTO pokemon (id, nome, tipo) VALUES(134, 'Vaporeon', 'Água');
INSERT INTO pokemon (id, nome, tipo) VALUES(135, 'Jolteon', 'Elétrico');
INSERT INTO pokemon (id, nome, tipo) VALUES(136, 'Flareon', 'Fogo');
INSERT INTO pokemon (id, nome, tipo) VALUES(137, 'Porygon', 'Normal');
INSERT INTO pokemon (id, nome, tipo) VALUES(138, 'Omanyte', 'Água-Pedra');
INSERT INTO pokemon (id, nome, tipo) VALUES(139, 'Omastar', 'Água-Pedra');
INSERT INTO pokemon (id, nome, tipo) VALUES(140, 'Kabuto', 'Água-Pedra');
INSERT INTO pokemon (id, nome, tipo) VALUES(141, 'Kabutops', 'Água-Peda');
INSERT INTO pokemon (id, nome, tipo) VALUES(142, 'Aerodactyl', 'Voador-Pedra');
INSERT INTO pokemon (id, nome, tipo) VALUES(143, 'Snorlax', 'Normal');
INSERT INTO pokemon (id, nome, tipo) VALUES(144, 'Articuno', 'Voador-Gelo');
INSERT INTO pokemon (id, nome, tipo) VALUES(145, 'Zapdos', 'Voador-Eletrico');
INSERT INTO pokemon (id, nome, tipo) VALUES(146, 'Moltres', 'Voador-Fogo');
INSERT INTO pokemon (id, nome, tipo) VALUES(147, 'Dratini', 'Dragão');
INSERT INTO pokemon (id, nome, tipo) VALUES(148, 'Dragonair', 'Dragão');
INSERT INTO pokemon (id, nome, tipo) VALUES(149, 'Dragonite', 'Dragão-Voador');
INSERT INTO pokemon (id, nome, tipo) VALUES(150, 'Mewtwo', 'Psiquico');
INSERT INTO pokemon (id, nome, tipo) VALUES(151, 'Mew', 'Psiquico');
